version: 1

disable_existing_loggers: False

formatters:

    simple:

        format: "%(asctime)s - %(module)s - %(funcName)s - %(lineno)d - %(levelname)s - %(message)s"

handlers:

    console:

        class: logging.StreamHandler

        level: DEBUG

        formatter: simple

        stream: ext://sys.stdout

    sys_file_handler:

        class: logging.handlers.TimedRotatingFileHandler

        level: INFO

        formatter: simple

        filename: C:/ALAITP/alaitp-co-occurrence-matrix/logs/alaitp-co-occurrence-matrix-info.log

        when: midnight

        interval: 1

        backupCount: 20

        encoding: utf8

    db_file_handler:

        class: logging.handlers.RotatingFileHandler

        level: INFO

        formatter: simple

        filename: C:/ALAITP/alaitp-co-occurrence-matrix/logs/alaitp-co-occurrence-matrix-db.log

        maxBytes: 104857600  # 100MB

        backupCount: 20

        encoding: utf8

    error_file_handler:

        class: logging.handlers.TimedRotatingFileHandler

        level: ERROR

        formatter: simple

        filename: C:/ALAITP/alaitp-co-occurrence-matrix/logs/alaitp-co-occurrence-matrix-error.log

        backupCount: 20

        encoding: utf8

        when: midnight

        interval: 1

loggers:

    fileLogger:

        level: DEBUG

        handlers: [console, sys_file_handler, error_file_handler]

        propagate: no

    dbLogger:

        level: DEBUG

        handlers: [console, db_file_handler, error_file_handler]

        propagate: no

root:

    level: INFO

    handlers: [console]

    propagate: 1